lib/igt_x86.c: Fix musl/uclibc build
Original patch was added to void-linux:
https://github.com/void-linux/void-packages/commit/ddfc1f66a0c571b420303c33aed29fd38ace4fc7

Fixes build error:
../lib/igt_x86.c:295:6: error: ‘ifunc’ is not supported on this target
  295 | void igt_memcpy_from_wc(void *dst, const void *src, unsigned long len)

Bug report with request to split the original patch into some
functional changes:
Link: https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/issues/138

Signed-off-by: Stefano Ragni <st3r4g@protonmail.com>
Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Reviewed-by: Kamil Konieczny <kamil.konieczny@linux.intel.com>