benchmarks/gem_exec_tracer.c: Fix musl build
Original patch was added to void-linux:
https://github.com/void-linux/void-packages/commit/111918317d06598fe1459dbe139923404f3f4b9d

Fixes build error:
../benchmarks/gem_exec_tracer.c:274:1: error: conflicting types for ‘ioctl’; have ‘int(int,  long unsigned int, ...)’
  274 | ioctl(int fd, unsigned long request, ...)

Bug report with request to split the original patch into some
functional changes:
Link: https://gitlab.freedesktop.org/drm/igt-gpu-tools/-/issues/138

Signed-off-by: Mohammed Anas <triallax@tutanota.com>
Signed-off-by: Bernd Kuhls <bernd@kuhls.net>
Reviewed-by: Kamil Konieczny <kamil.konieczny@linux.intel.com>